---
- name: Get a list of all running containers
  docker_host_info:
    containers: True
  register: docker_info

- name: Stop all running containers
  docker_container:
    name: '{{ item.Names[0] | regex_replace("^/", "") }}'
    state: stopped
  loop: '{{ docker_info.containers }}'
