---
- name: Stop geth
  command: "docker-compose stop geth"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"

- name: Start geth pruning
  command: "docker-compose -f geth-prune.yaml run geth-prune"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"

- name: Start geth
  command: "docker-compose --compatibility up -d geth"
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"

# EOF
