---
- name: Install expect
  apt:
    name: expect

- name: Run exit validator
  script: "{{ e2dc_install_path }}/lodestar_validator_exit.sh \"{{ validator_pubkey }}\""
  args:
    chdir: "{{ e2dc_install_path }}"
  become: yes
  become_user: "{{ stereum_user }}"
  ignore_errors: yes
  when: setups[setup].exit_account is defined
